spring:
  application:
    name: catalogs
  config: 
    name: ${spring.application.name}
  main: 
    allow-bean-definition-overriding: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Lalo3032
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Usa "update" durante el desarrollo, pero puedes usar "validate" o "none" para producción.
    show-sql: true # Muestra las consultas SQL ejecutadas por Hibernate
    properties:
      hibernate:
        format_sql: true # Formatea las consultas SQL