spring:
  application:
    name: notification
  config: 
    name: ${spring.application.name}
  main: 
    allow-bean-definition-overriding: true
    
  datasource:
    url: jdbc:postgresql://localhost:5432/notificacionesdb
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        springframework:
          jdbc:
            datasource: debug
   
  data:
    mongodb:
      uri: mongodb://localhost:27017/notificacionesdb